### ISSUE TITLE
Wallet Encrytion

### ISSUE THREAD

**Issue by limitingKano** [g0ssipcoin/GossipCoinCore#1]
My wallet fails to recognise my passphrase.  I know it's 100% correct.  There has been an update since adding it.  Could this be a bug?

**Comment by alexudm** [comment]
Hello! I have the same

**Comment by limitingKano** [comment]
I'm now considering the fact that I may have either unintentionally capitalised a letter or put a space in!  I'm currently trying to crack it using Thegrideon bitcoin password recovery, however I'm not totally surer I'm putting the correct parameters in.

**Comment by alexudm** [comment]
Sorry! It's OK. The wrong language was switched on

вс, 27 мая 2018 г., 16:01 limitingKano <notifications@github.com>:
